---
- name: default
  config:
    IdentityFile:
      - ~/.ssh/id_rsa
      - ~/.ssh/id_ed25519

- name: shared_host
  config:
    HostName: ssh.example.com

- host: a.example.com
  merge: [ default, shared_host ]
  config:
    Port: 1022
    HostKeyAlias: "{{ host[0] }}"

- host: b.example.com
  merge: [ default, shared_host ]
  config:
    Port: 2022
    HostKeyAlias: "{{ host[0] }}"

- match:
    originalhost: git.example.com
    exec: ~/.ssh/check_work.py
  config:
    ProxyJump: a.example.com

- host:
    - git.example.com
    - github.com
  config:
    User: git
    RequestTTY: 'no'  # str, not bool
    IdentityFile:
      - ~/.ssh/git_rsa
      - ~/.ssh/git_ed255519
